---
title: "Data"
output: 
   html_document:
     toc: true
     toc_float:
       collapsed: false
     includes:
       after_body: footerEA.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, message=FALSE, warning=FALSE)
library(JMbayes)
library(lattice)
library(splines)
library(survminer)
```

The pbc2 and pbc2.id data sets are used from the <code>JMbayes</code> package in <code>R</code>. 
The long format data set is called <code>pbc2</code>: 
```{r}
head(pbc2)
```

The wide format data set is called <code>pbc2.id</code>. 
```{r}
head(pbc2.id)
```

# Longitudinal outcome

```{r}
p1 <- xyplot(log(serBilir) ~ year, groups = id, 
             data = pbc2[pbc2$status %in% c("dead", "transplanted"), ], xlim = c(0, 15),
             col = "grey", lwd = 1, type = "l",
             ylab = list(label = "Logarithmic scale of serum Bilirubin", cex = 1.2), 
             xlab = list(label = "Years", cex = 1.2),
             main = list(label = "Dead or transplanted patients", cex = 1.04),
             panel = function(x, y,...) {
                 panel.xyplot(x, y, ...)
                 panel.xyplot(pbc2$year[pbc2$status %in% c("dead", "transplanted")], 
                              log(pbc2$serBilir[pbc2$status %in% c("dead", "transplanted")]), 
                              col = 1, lwd = 3, type = "smooth")
       })

p2 <- xyplot(log(serBilir) ~ year, groups = id, 
             data = pbc2[pbc2$status %in% c("alive"), ], xlim = c(0, 15),
             col = "grey", lwd = 1, type = "l",
             ylab = list(label = "Logarithmic scale of serum Bilirubin", cex = 1.2), 
             xlab = list(label = "Years", cex = 1.2),
             main = list(label = "Alive patients", cex = 1.04),
             panel = function(x, y,...) {
                 panel.xyplot(x, y, ...)
                 panel.xyplot(pbc2$year[pbc2$status %in% c("alive")], 
                              log(pbc2$serBilir[pbc2$status %in% c("alive")]), 
                              col = 1, lwd = 3, type = "smooth")
       })

p3 <- histogram(~pbc2[pbc2$status %in% c("dead", "transplanted"), "years"], data = pbc2,
       type = "density", xlim = c(0, 15), 
       xlab = "Event time",
       main = "", col = "grey")

print(p1, position=c(0, 0.3, 0.5, 1), more=TRUE)
print(p2, position=c(0.5, 0.3, 1, 1), more=TRUE)
print(p3, position=c(0, 0, 0.5, 0.3))

```


```{r}
fit_linear <- lme(serBilir ~ year, random = ~ year | id, data = pbc2)
fit_nonlinear <- lme(serBilir ~ ns(year, 3), random = list(id = pdDiag(form = ~ ns(year, 3))), data = pbc2)

pbc2$fitted_linear <- fitted(fit_linear)
pbc2$fitted_nonlinear <- fitted(fit_nonlinear)

newdata <- pbc2[pbc2$id %in% c(128, 142, 46, 57, 216, 93, 114, 120, 294), ]

xyplot(serBilir ~ year | id, data = newdata, pch = 20, 
       subscripts = TRUE, col = 1, lwd = 3, strip = FALSE, cex = 1.5,
       ylab = list(label = "Serum Bilirubin", cex = 1.2),
       xlab = list(label = "Years", cex = 1.2),
       panel = function(x, y, subscripts = subscripts,...) {
         panel.xyplot(x, y, subscripts = subscripts, ...)
         panel.lines(newdata$year[subscripts], newdata$fitted_linear[subscripts], 
                     col = "red", lwd = 4, lty = 1)
         panel.lines(newdata$year[subscripts], newdata$fitted_nonlinear[subscripts], 
                     col = "blue", lwd = 4, lty = 2)
})
```

re# Survival outcome

```{r}
fit <- survfit(Surv(years, status2) ~ 1, data = pbc2.id)
ggsurvplot(fit, data = pbc2.id, risk.table = TRUE, palette = "black", legend = "none")
```

